#!/usr/bin/env bash

set -eo pipefail

# Find all releases that are $major.$minor(.$patch)? (no rcs)
curl -fs https://api.github.com/repos/GitTools/GitVersion/releases \
  | jq -r '.[].tag_name' \
  | sed 's/^v//' \
  | grep -v '-' \
  > src/gitversion-versions.txt
