#!/bin/bash

set -eo pipefail

version=$1

cd /tmp
wget https://github.com/GitTools/GitVersion/releases/download/$version/gitversion-linux-x64-$version.tar.gz
tar xfv gitversion-linux-x64-$version.tar.gz
sudo mv GitVersion /usr/local/bin
